# python-2.7

FROM debian:jessie

# Install into the system the tools necessary to build apache and python.
RUN rm -r /var/lib/apt/lists/* && apt-get update && \
	apt-get install -y ca-certificates locales libssl1.0.0 curl gcc file \
		libc6-dev libssl-dev make xz-utils zlib1g-dev libbz2-dev \
		libsqlite3-dev libpcre++0 libpcre++-dev python-pip \
		python-virtualenv virtualenv libldap2-dev \
		--no-install-recommends && \
		rm -r /var/lib/apt/lists/*

RUN echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen && locale-gen

ENV LANG en_US.UTF-8

# Get buildout installed under /build
RUN mkdir -p /build && virtualenv /build/env
COPY requirements.txt /build/
WORKDIR /build
RUN (PATH=/build/env/bin:$PATH; \
	pip install -U -r requirements.txt && buildout init)

# Install apache and python under /whiskey
COPY buildout-2.7.cfg /build/buildout.cfg
RUN PATH=/build/env/bin:$PATH buildout -v -v

# Cleanup the stuff that was only needed temporarily.
WORKDIR /app
RUN apt-get purge -y python.* libpython.* virtualenv

# Get pip installed in our new python location (under /whiskey) and
# remove stuff that would just bloat our image.
ENV PATH=/whiskey/python/bin:$PATH \
	PYTHONHASHSEED=random \
	WSGI_RUN_USER=www-data \
	WSGI_RUN_GROUP=www-data
RUN curl -SL 'https://bootstrap.pypa.io/get-pip.py' | python && \
	 find /whiskey/python/lib \
		\( -type d -and -name test -or -name tests \) -or \
		\( -type f -and -name '*.pyc' -or -name '*.pyo' \) | \
		xargs -r rm -rf && \
	 rm -rf /build

# Store scripts that may be used to start a shell or in an 'onbuild' image.
COPY bin/* /whiskey/python/bin/
